### ISSUE TITLE
[Safari] MP4 don't play in share-link

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/files_videoplayer#41] opened 2016-03-14 17:42 UTC
I run oC 9.0, uploaded a *.mp4 file and shared it by link:
http://mst.works/oc/index.php/s/RaEjK1hnsjksGIN

This Video plays in Chrome (Chrome 49, Mac OS X 10.11.3), but not in Safari (Safari in iOS 9.2.1 AND Safari 9.0.3, Mac OS X).

The video itself plays in Chrome and Safari:
http://mst.works/mp4-movie-test/BigBuckBunny_320x180.mp4

It also plays in the files app in Safari. I see the same behaviour in 8.2.2.

@MorrisJobke Who can help here?

00005013 [blue-ticket]

**Comment by MorrisJobke** [comment] 2016-03-15 07:37
cc @LukasReschke

**Comment by Instagit** [comment] 2016-03-15 12:35
The public share page uses the browser's default video player so this isn't related to the files_videoplayer app.

I tried it at work with a H264/AAC mp4 video that works in all other browsers and was able to reproduce the problem in Safari: The video element is there, but the video doesn't load. To me it looks like a problem with Safari, not the page, but I don't own any Apple devices to further look into this.

**Comment by michaelstingl** [comment] 2016-03-15 13:30
@Instagit Safari plays the video in the files app and plays it without ownCloud.

> The video itself plays in Chrome and Safari:
> http://mst.works/mp4-movie-test/BigBuckBunny_320x180.mp4
> 
> It also plays in the files app in Safari. I see the same behaviour in 8.2.2.

**Comment by MorrisJobke** [comment] 2016-03-15 13:40
@LukasReschke any findings on your side?

**Comment by Instagit** [comment] 2016-03-15 14:25
>@Instagit Safari plays the video in the files app and plays it without ownCloud.

Safari has the weirdest bugs and design deficiencies, so that doesn't say much. The video link has a different format on the public share page, maybe it can't handle that properly.

**Comment by LukasReschke** [comment] 2016-03-15 15:49
Safari requires HTTP Range requests, the endpoint used at `\OCA\Files_Sharing\Controllers\ShareController::downloadShare` doesn't support it. Thus no video is displayed.

Now the fun stuff starts, technically it would be easy to do something like:
```
<source src="http://b378zUCKQ3G9vn4:@localhost/oc/public.php/webdav" type="<?php p($_['mimetype']); ?>" />
```

However, Safari will then try to be clever and again ask you for your credentials. So one sees the following then:
![2016-03-15_16-00-56](https://cloud.githubusercontent.com/assets/878997/13782383/1f4e3046-eac7-11e5-8f01-7b1aa5d649d4.png)

And also Chrome kinda behaves like that. Technically the streaming would however work greatly.

So what we need is a new public WebDAV endpoint that has something like `public.php/share/$SHAREID/`. We can then simply link to that instead of any Basic Auth hackery…

cc @DeepDiver1975 @icewind1991

**Comment by LukasReschke** [comment] 2016-03-15 15:55
Opened ticket in core at https://github.com/owncloud/core/issues/23269

**Comment by Instagit** [comment] 2016-04-04 08:46
You can right click the video and "copy video location" or look at the source tags to get a link to the MP4, but it will be offered as a download and not play in the browser.

**Comment by kriztan** [comment] 2016-04-10 18:38
Hi, i've a similar problem with OC 9 and a shared folder which contains videos. The MP4 files could not be played with the video player, images inside this folder where displayed correctly.
Is this related to this bug or another bug?

**Comment by michaelstingl** [comment] 2016-04-11 08:20
@kriztan Which browser did you tested?

**Comment by kriztan** [comment] 2016-04-11 08:25
@michaelstingl I've testde it with Chrome on a Windows 7 mashine. The videos could be played after logging in, but not when they are insinde a shared folder.

**Comment by michaelstingl** [comment] 2016-04-11 08:55
@kriztan This sounds like a different issue.

**Comment by kriztan** [comment] 2016-04-11 08:58
@michaelstingl Thanks, I've opened a new issue #45

**Comment by lenz1111** [comment] 2016-04-28 11:16
his is due to an unsupported http range requests. Temporary solution (tested on 9.0.1) - that add support for this:
[owncloud9_download_http_range.zip](https://github.com/owncloud/files_videoplayer/files/240383/owncloud9_download_http_range.zip)

**Comment by michaelstingl** [comment] 2016-04-28 12:10
@lenz1111 Could you post this in https://github.com/owncloud/core/issues/23269 too? /cc @LukasReschke

**Comment by lenz1111** [comment] 2016-04-28 12:15
This https://github.com/owncloud/core/issues/23269 is different issue - DAV endpoint for public shares could also solve problem - my solution do it in different way...

**Comment by lenz1111** [comment] 2016-04-29 12:38
Opened a pull request with my modifications https://github.com/owncloud/core/pull/24354
Pull request is for core module (not files_videoplayer)

**Comment by felixboehm** [comment] 2016-05-18 14:16
@cmonteroluque @MTRichards Please provide a milestone here

**Comment by MTRichards** [comment] 2016-05-18 15:48
What is the priority of the problem?  @michaelstingl @felixboehm 
Is the PR here what is needed to fix the problem? @PVince81 @cmonteroluque @DeepDiver1975

**Comment by michaelstingl** [comment] 2016-05-18 15:52
A few weeks ago, @LukasReschke investigated this here: https://github.com/owncloud/core/issues/23269

**Comment by PVince81** [comment] 2016-05-18 16:01
If the video plays in other browsers than Safari, then I doubt that it's a range request issue, unless the video library is using a different approach for Safari that itself needs range requests.

Would be good if someone with that Safari version could test this PR: https://github.com/owncloud/core/pull/24354

**Comment by PVince81** [comment] 2016-05-18 16:02
@owncloud/qa can you help testing this ? (mp4 + safari + share link + https://github.com/owncloud/core/pull/24354)

**Comment by michaelstingl** [comment] 2016-05-18 16:09
If you could send me a link to a patched ownCloud, I would be happy to test.

**Comment by PVince81** [comment] 2016-05-18 16:10
I think @SergioBertolinSG or @davitol have access to Macs so they should be able to help testing this on a patched server.

**Comment by lenz1111** [comment] 2016-05-18 16:34
It all depends on the type of video. I can create video with flags `-movflags faststart` that works without range request support on _Chrome_, but without this flag it will not play until I will add range request support. Android browser requires range requests support for both versions. I can give you test link to video with modified owncloud with range requests support.

**Comment by michaelstingl** [comment] 2016-05-18 16:53
@lenz1111 A test link from a patched ownCloud instance would be very cool. Then I could compare it with [my (unpatched) link](http://mst.works/oc/index.php/s/RaEjK1hnsjksGIN). Thanks for your help!

BTW do you know how to check if a video file has `-movflags faststart` set?

**Comment by lenz1111** [comment] 2016-05-18 17:02
@michaelstingl I don't know how to check how video was created (never done this before).
Link to public share on my ownCloud instance:
https://cloud.lenzdevelopment.pl/index.php/s/g4MY0pf7Bk9Vwbe#

**Comment by lenz1111** [comment] 2016-05-18 17:07
Single file share:
https://cloud.lenzdevelopment.pl/index.php/s/WICMaFEduf57GM6

**Comment by michaelstingl** [comment] 2016-05-18 17:10
Yay, both links work on the Desktop! (Safari 9.1 on Mac OS X 10.11.4)

**Comment by michaelstingl** [comment] 2016-05-18 17:14
…and both links play in mobile Safari in iOS 9.3 (SimulatorApp-645.9) – @lenz1111 Thanks again!!!

**Comment by lenz1111** [comment] 2016-05-18 17:15
try again (first link) - I share file downloaded from your site

**Comment by michaelstingl** [comment] 2016-05-18 17:24
@lenz1111 My video plays in the Desktop Safari, but with some delay. Maybe the `-movflags faststart` isn't set correctly. But the issue seems to be solved with the PR.

**Comment by davitol** [comment] 2016-05-19 11:10
https://github.com/owncloud/files_videoplayer/issues/47
So I think it is not a browser problem

**Comment by michaelstingl** [comment] 2016-05-19 11:39
> So I think it is not a browser problem

Safari on desktop and mobile uses special method to play/stream supported video files. In the current oC, this isn't supported with share-links. @lenz1111 tested https://github.com/owncloud/core/pull/24354 , which fixed the issue.

**Comment by lenz1111** [comment] 2016-05-19 11:52
@davitol https://github.com/owncloud/files_videoplayer/issues/47 is probably a different issue. When you are logged in then files_videoplayer uses _webdav_ to stream movie (it has range request support). The only problem is that in the shared links _webdav_ is not used. So if you cannot see movie preview as logged user then it is problem related to usupported video format by browser.

**Comment by davitol** [comment] 2016-05-19 11:53
@michaelstingl @lenz1111 THX for the info 🍺

**Comment by lenz1111** [comment] 2016-05-19 11:56
@davitol We can create preview for every uploaded movie - for example in this way: https://github.com/owncloud/core/issues/24480 - that could solve your problem.

**Comment by davitol** [comment] 2016-05-19 12:28
@lenz1111 I' ve applied on oC daily-master these patches:
https://github.com/lenz1111/files_videoplayer/commit/d3632a0565e1aee09d8c1b87ddc9e98d923a8252
and
https://github.com/owncloud/core/compare/master...lenz1111:video_transcode

And I've tried to reproduce a mp4 file in Safari on OSX and iOS and it did not worked for me 😢 

Maybe other reviewer can have a try...

**Comment by lenz1111** [comment] 2016-05-19 13:35
@davitol It had a bug in the repo... check and try again (see comments in https://github.com/owncloud/core/issues/24480)

**Comment by michaelstingl** [comment] 2016-05-19 13:52
@davitol @lenz1111 Do you mix 2 separate issues here?

This issue (https://github.com/owncloud/files_videoplayer/issues/41) isn't about previews. As I understood, a fix could be in https://github.com/owncloud/core/pull/24354 .

The other things with previews etc are unrelated to this issue:
- https://github.com/owncloud/core/pull/24354
- https://github.com/lenz1111/files_videoplayer/commit/d3632a0565e1aee09d8c1b87ddc9e98d923a8252
- https://github.com/owncloud/core/compare/master...lenz1111:video_transcode

Please correct me if I'm wrong. I'm also available in [#owncloud-dev](https://webchat.freenode.net/?channels=owncloud-dev) and [#owncloud-testing](https://webchat.freenode.net/?channels=owncloud-testing) (IRC).

**Comment by lenz1111** [comment] 2016-05-19 14:01
@michaelstingl You're right - 'Preview' is unrelaed here - I just only awswered @davtol and moved to correct issue...

**Comment by davitol** [comment] 2016-05-23 12:37
@michaelstingl it WFM applying https://github.com/owncloud/core/pull/24750

Great work @lenz1111 👍

**Comment by michaelstingl** [comment] 2016-05-23 12:51
@davitol nice!

**Comment by PVince81** [comment] 2016-05-25 09:11
PR was merged, closing

**Closed by PVince81** 2016-05-25 09:11 UTC
Labels: bug, green-ticket

**Comment by PVince81** [comment] 2016-05-25 09:19
stable9 backport here: https://github.com/owncloud/core/pull/24830
